FROM node:20

WORKDIR /app

RUN npm install -g @uppy/companion

COPY companion.config.json .

EXPOSE 3020

ENV COMPANION_SECRET=skillanthropy
ENV COMPANION_DOMAIN=http://localhost:3020
ENV COMPANION_ALLOW_LOCAL_URLS=true
ENV COMPANION_DATADIR="/app/uploads"
RUN mkdir /app/uploads


CMD ["companion", "--config", "companion.config.json"]