name: skillanthropy
services:
  app:
    image: theignorantview/skillanthropy:v0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    
