version: "3.8"
name: "companion"
services:
  companion:
    container_name: "companion"
    image: docker.io/transloadit/companion:latest
    ports:
      - "3020:3020"
    env_file:
      - .env.companion
    volumes:
      - companion-data:/mnt/companion-data
volumes:
  companion-data:
